num_epochs:
  confdir: 'configs'
  type: 'categorical'
  choices: [10]
#idx:
#  confdir: 'configs'
#  type: 'int'
#  min: 49
#  max: 49
#seed:
#  confdir: 'configs'
#  type: 'int'
#  min: 42
#  max: 42
d_model:
  confdir: 'model'
  type: 'categorical'
  choices: [128]
dim_feedforward:
  confdir: 'model'
  type: 'categorical'
  choices: [128]
n_head:
  confdir: 'model'
  type: 'categorical'
  choices: [4]
num_layers:
  confdir: 'model'
  type: 'categorical'
  choices: [1]
dropout:
  confdir: 'model'
  type: 'float'
  min: 0.2
  max: 0.2
  log: false
lr:
  confdir: 'model'
  type: 'float'
  min: 0.001
  max: 0.02
  log: true