num_epochs:
  type: 'categorical'
  choices: [10]
d_model:
  type: 'categorical'
  choices: [128]
n_head:
  type: 'categorical'
  choices: [4]
dim_feedforward:
  type: 'categorical'
  choices: [128]
num_layers:
  type: 'categorical'
  choices: [1]
dropout:
  type: 'float'
  min: 0.2
  max: 0.2
  log: false
lr:
  type: 'float'
  min: 0.00001
  max: 0.01
  log: true
idx:
  type: 'int'
  min: 2663
  max: 2663