num_epochs:
  confdir: 'configs'
  type: 'categorical'
  choices: [10]
#idx:
#  confdir: 'configs'
#  type: 'int'
#  min: 49
#  max: 49
#seed:
#  confdir: 'configs'
#  type: 'int'
#  min: 42
#  max: 42
d_model:
  confdir: 'model'
  type: 'categorical'
  choices: [32, 64, 128, 512]
dim_feedforward:
  confdir: 'model'
  type: 'categorical'
  choices: [32, 64, 128, 512]
n_head:
  confdir: 'model'
  type: 'categorical'
  choices: [4, 8, 16]
num_layers:
  confdir: 'model'
  type: 'categorical'
  choices: [1, 2, 3, 4]
dropout:
  confdir: 'model'
  type: 'float'
  min: 0.1
  max: 0.8
  log: false
lr:
  confdir: 'model'
  type: 'float'
  min: 0.001
  max: 0.1
  log: true