defaults:
  - _self_
  - config.yaml
  - hyperparameters: hyperparameters.yaml

hydra:
  run:
    dir: .outputs/${hydra.job.name}/data_${data}_model_${model}

direction: 'maximize'
n_trials: 100000
timeout: 360000
