defaults:
  - _self_
  - model: RawTransformer.yaml

hydra:
  run:
    dir: .outputs/${hydra.job.name}/data_${data}_model_${model}

data: 'Cora'
data_root: './data/'
exp_name: ???
save_dir: '.outputs'
process_method: 'se_ordering'
device: 'cuda'
show_log: true
save_ckpt: false
seed: 42
num_epochs: 10
idx: 90
