hydra:
  run:
    dir: .outputs/${hydra.job.name}/data_${data}_model_${model}

data: 'Cora'
data_root: './data/'
exp_name: ???
save_dir: '.outputs'
process_method: 'se_ordering'
model: 'RawTransformer'
loss_fn: 'NLLLoss'
optimizer: 'Adam'
device: 'cuda'
seed: 86
d_model: 256
dim_feedforward: 64
n_head: 4
num_layers: 2
num_epochs: 10
show_log: true
save_ckpt: false
dropout: 0.3516848137314512
lr: 0.0016807989542709457
idx: 94
